# Generated by Django 2.0 on 2017-12-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can mark returned”', 'Set Book as returned'),), 'verbose_name': 'Book', 'verbose_name_plural': 'Books copie'},
        ),
    ]
