# Generated by Django 2.0 on 2017-12-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20171205_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='media'),
        ),
    ]
