# Generated by Django 2.0 on 2018-01-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20171211_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(default='media/default.pdf', upload_to='pdfs'),
        ),
    ]
