# Generated by Django 2.0 on 2018-01-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can mark returned”', 'Set Book as returned'),), 'verbose_name': 'Book', 'verbose_name_plural': 'Books Borrow'},
        ),
        migrations.AddField(
            model_name='book',
            name='copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='pdfs'),
        ),
    ]
