# Generated by Django 2.0 on 2018-01-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_borrowedbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can mark returned”', 'Set Book as returned'),), 'verbose_name': 'Book', 'verbose_name_plural': 'Books second'},
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='due_back',
            field=models.DateField(blank=True, null=True),
        ),
    ]
